title:             CvSU Generals
email:             freedclythe@gmail.com
description:       Truth | Excellence | Service
author:            Generals
baseurl:           "/"
url:               "http://nathanjf-vi.github.io"

# Social Profiles
github_username:   NathanJF-VI

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
